[package]
name = "ppa6-print"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
cosmic-text = "0.12.1"
clap = { version = "4.5.28", features = ["derive"] }
clap-num = "1.2.0"
image = "0.25.5"
itertools = "0.14.0"
open = "5.3.2"
ppa6.workspace = true
