[package]
name = "ppa6-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
ppa6 = { version = "0.1.0", path = "../ppa6" }
iced = { version = "0.13.1", features = ["advanced", "image"] }
anyhow = "1.0.95"
